### PR TITLE
log file name fix

### PR DESCRIPTION
**Pull request by devidask27**
consol output
root@devidas-test-ubuntu16:/home/ubuntu/pf9/log# ls
pf9ctl-20210227.log   pf9ctl-2021102.log

### CODE REVIEW

**Comment by devidask27** [comment]
Output
root@devidas-test-ubuntu16:/home/ubuntu/pf9/log# ls
pf9ctl-20210203.log    pf9ctl-20210227.log

**Review by anupbarve — APPROVED** [review]

**Review by nikhilbandi — COMMENTED** [review]
Change looks good.
Please test after setting machine date to some different value other than today and make sure the log file with same date gets created.

**Review by nikhilbandi — COMMENTED** [review]
Also, please make sure for different dates, different log files get generated even though there are log files present for earlier dates. Do check if the logs for a particular date are written on the file with the same date only.

**Comment by devidask27** [comment]
> Change looks good.
> Please test after setting machine date to some different value other than today and make sure the log file with same date gets created.

yes i tested this. different log file is getting created for different date.

**Pull request merged**
